<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="lidar" params="parent">

    <link name="lidar_pedestal_link">
      <visual><geometry><cylinder radius="${lidar_ped_radius}" length="${lidar_ped_height+0.15}"/></geometry><material name="gray"/></visual>
      <collision><geometry><cylinder radius="${lidar_ped_radius}" length="${lidar_ped_height}"/></geometry></collision>
    </link>

    <joint name="lidar_pedestal_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="lidar_pedestal_link"/>
      <origin xyz="${lidar_x} 0 ${lidar_ped_half+0.05}" rpy="0 0 0"/>
    </joint>

    <link name="lidar_link">
      <visual><geometry><cylinder radius="0.035" length="0.05"/></geometry><material name="black"/></visual>
      <collision><geometry><cylinder radius="0.035" length="0.05"/></geometry></collision>
    </link>

    <joint name="lidar_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="lidar_link"/>
      <origin xyz="${lidar_x} 0 ${lidar_z}" rpy="0 0 0"/>
    </joint>

    <!-- Optional standard frame name for Nav2 and sensors -->
    <link name="laser_frame"/>
    <joint name="laser_frame_joint" type="fixed">
      <parent link="lidar_link"/>
      <child link="laser_frame"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

  </xacro:macro>

</robot>