<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="base_length" value="0.75"/>
  <xacro:property name="base_height" value="0.20"/>

  <xacro:property name="depth_camera_width"  value="0.12"/>
  <xacro:property name="depth_camera_depth"  value="0.04"/>
  <xacro:property name="depth_camera_height" value="0.04"/>

  <xacro:macro name="depth_camera" params="parent">
    <link name="depth_camera_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${depth_camera_depth} ${depth_camera_width} ${depth_camera_height}"/>
        </geometry>
        <material name="sensor_black">
          <color rgba="0.05 0.05 0.05 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${depth_camera_depth} ${depth_camera_width} ${depth_camera_height}"/>
        </geometry>
      </collision>
    </link>

    <joint name="depth_camera_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="depth_camera_link"/>
      <!-- forward-front mount -->
      <origin
        xyz="${base_length/2.0 + depth_camera_depth/2.0 + 0.01} 0 ${base_height/2.0 - depth_camera_height/2.0}"
        rpy="0 0 0"/>
    </joint>
  </xacro:macro>

</robot>
