<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="lidar_radius" value="0.055"/>
  <xacro:property name="lidar_height" value="0.05"/>
  <xacro:property name="base_height"  value="0.20"/>

  <xacro:macro name="lidar" params="parent">
    <link name="lidar_link">
      <visual>
        <origin xyz="0 0 ${lidar_height/2.0}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
        </geometry>
        <material name="sensor_blue">
          <color rgba="0.1 0.3 0.6 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${lidar_height/2.0}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
        </geometry>
      </collision>
    </link>

    <joint name="lidar_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="lidar_link"/>
      <origin xyz="0 0 ${base_height/2.0 + lidar_height/2.0 + 0.01}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

</robot>
