<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="base_length" value="0.75"/>
  <xacro:property name="base_width"  value="0.60"/>
  <xacro:property name="base_height" value="0.20"/>
  <xacro:property name="ground_clearance" value="0.03"/>

  <!-- Helpful inertia macro (simple box) -->
  <xacro:macro name="inertial_box" params="m x y z">
    <inertial>
      <mass value="${m}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <!-- Box inertia approximation -->
      <inertia
        ixx="${m/12.0*(y*y+z*z)}"
        iyy="${m/12.0*(x*x+z*z)}"
        izz="${m/12.0*(x*x+y*y)}"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="base">
    <link name="base_footprint"/>

    <link name="base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        <material name="chassis_green">
          <color rgba="0.15 0.45 0.25 1.0"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
      </collision>

      <!-- optional mass for RViz/robot_state_publisher sanity -->
      <xacro:inertial_box m="12.0" x="${base_length}" y="${base_width}" z="${base_height}"/>
    </link>

    <!-- base_footprint at ground, base_link centered in chassis above it -->
    <joint name="base_footprint_joint" type="fixed">
      <parent link="base_footprint"/>
      <child link="base_link"/>
      <origin xyz="0 0 ${base_height/2.0 + ground_clearance}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

</robot>
