<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  
  <xacro:property name="half_pi" value="${pi/2.0}"/>

  <xacro:property name="base_length" value="0.75"/>
  <xacro:property name="base_width"  value="0.60"/>
  <xacro:property name="base_height" value="0.20"/>
  <xacro:property name="ground_clearance" value="0.03"/>

  <xacro:property name="wheel_radius" value="0.12"/>
  <xacro:property name="wheel_width"  value="0.06"/>
  <xacro:property name="wheel_x_offset" value="0.16"/>

  <xacro:property name="wheel_z" value="${wheel_radius - base_height/2.0 - ground_clearance}"/>
  <xacro:property name="wheel_y" value="${base_width/2.0 + wheel_width/2.0}"/>

  <xacro:macro name="inertial_cyl" params="m r l">
    <inertial>
      <mass value="${m}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
        ixx="${(1/12.0)*m*(3*r*r + l*l)}"
        iyy="${(1/12.0)*m*(3*r*r + l*l)}"
        izz="${0.5*m*r*r}"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="wheel" params="name x y">
    <link name="${name}">
      <visual>
        <!-- cylinder axis along Z by default, rotate so it matches wheel -->
        <origin xyz="0 0 0" rpy="${half_pi} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="wheel_black">
          <color rgba="0.1 0.1 0.1 1.0"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${half_pi} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>

      <xacro:inertial_cyl m="1.0" r="${wheel_radius}" l="${wheel_width}"/>
    </link>

    <!-- Revolute for simulation; for pure RViz it is okay -->
    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} ${wheel_z}" rpy="0 0 0"/>
      <!-- wheel spins around Y after our visual rotation -->
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="wheels">
    <xacro:wheel name="front_left_wheel"  x="${ base_length/2.0 - wheel_x_offset}" y="${ wheel_y}"/>
    <xacro:wheel name="rear_left_wheel"   x="${-base_length/2.0 + wheel_x_offset}" y="${ wheel_y}"/>
    <xacro:wheel name="front_right_wheel" x="${ base_length/2.0 - wheel_x_offset}" y="${-wheel_y}"/>
    <xacro:wheel name="rear_right_wheel"  x="${-base_length/2.0 + wheel_x_offset}" y="${-wheel_y}"/>
  </xacro:macro>

</robot>
