<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find robot_description)/urdf/arm/gripper.xacro"/>

  <xacro:macro name="arm_6dof" params="parent prefix xyz rpy">

    <xacro:property name="arm_base_height" value="0.08"/>
    <xacro:property name="arm_base_radius" value="0.06"/>

    <xacro:property name="link_radius" value="0.035"/>
    <xacro:property name="link1_length" value="0.20"/>
    <xacro:property name="link2_length" value="0.18"/>
    <xacro:property name="link3_length" value="0.16"/>
    <xacro:property name="link4_length" value="0.12"/>
    <xacro:property name="link5_length" value="0.10"/>
    <xacro:property name="link6_length" value="0.08"/>

    <!-- Arm base -->
    <link name="${prefix}base_link">
      <visual>
        <origin xyz="0 0 ${arm_base_height/2.0}" rpy="0 0 0"/>
        <geometry><cylinder radius="${arm_base_radius}" length="${arm_base_height}"/></geometry>
        <material name="arm_base"><color rgba="0.25 0.25 0.25 1.0"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 ${arm_base_height/2.0}" rpy="0 0 0"/>
        <geometry><cylinder radius="${arm_base_radius}" length="${arm_base_height}"/></geometry>
      </collision>
    </link>

    <joint name="${prefix}mount_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${prefix}base_link"/>
      <origin xyz="${xyz}" rpy="${rpy}"/>
    </joint>

    <!-- Joint 1 -->
    <link name="${prefix}link_1">
      <visual><origin xyz="0 0 ${link1_length/2.0}"/><geometry><cylinder radius="${link_radius}" length="${link1_length}"/></geometry><material name="arm_link"><color rgba="0.7 0.7 0.7 1.0"/></material></visual>
      <collision><origin xyz="0 0 ${link1_length/2.0}"/><geometry><cylinder radius="${link_radius}" length="${link1_length}"/></geometry></collision>
    </link>
    <joint name="${prefix}joint_1" type="revolute">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}link_1"/>
      <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="-3.1416" upper="3.1416" effort="10" velocity="1.0"/>
    </joint>

    <!-- Joint 2 -->
    <link name="${prefix}link_2">
      <visual><origin xyz="0 0 ${link2_length/2.0}"/><geometry><cylinder radius="${link_radius}" length="${link2_length}"/></geometry><material name="arm_link"/></visual>
      <collision><origin xyz="0 0 ${link2_length/2.0}"/><geometry><cylinder radius="${link_radius}" length="${link2_length}"/></geometry></collision>
    </link>
    <joint name="${prefix}joint_2" type="revolute">
      <parent link="${prefix}link_1"/>
      <child link="${prefix}link_2"/>
      <origin xyz="0 0 ${link1_length}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-1.5708" upper="1.5708" effort="10" velocity="1.0"/>
    </joint>

    <!-- Joint 3 -->
    <link name="${prefix}link_3">
      <visual><origin xyz="0 0 ${link3_length/2.0}"/><geometry><cylinder radius="${link_radius}" length="${link3_length}"/></geometry><material name="arm_link"/></visual>
      <collision><origin xyz="0 0 ${link3_length/2.0}"/><geometry><cylinder radius="${link_radius}" length="${link3_length}"/></geometry></collision>
    </link>
    <joint name="${prefix}joint_3" type="revolute">
      <parent link="${prefix}link_2"/>
      <child link="${prefix}link_3"/>
      <origin xyz="0 0 ${link2_length}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-1.5708" upper="1.5708" effort="10" velocity="1.0"/>
    </joint>

    <!-- Joint 4 -->
    <link name="${prefix}link_4">
      <visual><origin xyz="0 0 ${link4_length/2.0}"/><geometry><cylinder radius="${link_radius}" length="${link4_length}"/></geometry><material name="arm_link"/></visual>
      <collision><origin xyz="0 0 ${link4_length/2.0}"/><geometry><cylinder radius="${link_radius}" length="${link4_length}"/></geometry></collision>
    </link>
    <joint name="${prefix}joint_4" type="revolute">
      <parent link="${prefix}link_3"/>
      <child link="${prefix}link_4"/>
      <origin xyz="0 0 ${link3_length}" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit lower="-3.1416" upper="3.1416" effort="10" velocity="1.0"/>
    </joint>

    <!-- Joint 5 -->
    <link name="${prefix}link_5">
      <visual><origin xyz="0 0 ${link5_length/2.0}"/><geometry><cylinder radius="${link_radius}" length="${link5_length}"/></geometry><material name="arm_link"/></visual>
      <collision><origin xyz="0 0 ${link5_length/2.0}"/><geometry><cylinder radius="${link_radius}" length="${link5_length}"/></geometry></collision>
    </link>
    <joint name="${prefix}joint_5" type="revolute">
      <parent link="${prefix}link_4"/>
      <child link="${prefix}link_5"/>
      <origin xyz="0 0 ${link4_length}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-1.5708" upper="1.5708" effort="10" velocity="1.0"/>
    </joint>

    <!-- Joint 6 -->
    <link name="${prefix}link_6">
      <visual><origin xyz="0 0 ${link6_length/2.0}"/><geometry><cylinder radius="${link_radius}" length="${link6_length}"/></geometry><material name="arm_link"/></visual>
      <collision><origin xyz="0 0 ${link6_length/2.0}"/><geometry><cylinder radius="${link_radius}" length="${link6_length}"/></geometry></collision>
    </link>
    <joint name="${prefix}joint_6" type="revolute">
      <parent link="${prefix}link_5"/>
      <child link="${prefix}link_6"/>
      <origin xyz="0 0 ${link5_length}" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit lower="-3.1416" upper="3.1416" effort="10" velocity="1.0"/>
    </joint>

    <!-- Gripper attached at end -->
    <xacro:simple_gripper
      parent="${prefix}link_6"
      prefix="${prefix}gripper_"
      xyz="0 0 ${link6_length}"
      rpy="0 0 0"/>

  </xacro:macro>

</robot>
